import random
#rock paper Scissors game
#one is input from user 
# another is random generated by computer

rock1=''' 🪨🪨🪨🪨🪨'''
paper1=''' 📜📜📜📜📜'''             #these line is for fun purpos
scissor1=''' ✂️✂️✂️✂️✂️'''



game_image=[rock1,paper1,scissor1]    # this line is to put in list and excess them 
print('rock is 0')
print('paper is 1')                    #these line is for guideline
print('scissor is 2')
computer=int(random.randint(0,2))      #to generate random number
your=int(input('Enter the choice'))     #our input
print(game_image[your],'is your choice')  
print(game_image[your],'is your choice')  
print(game_image[your],'is your choice')  

if your==0 and computer==2:                #main logic
    print('You win ☺️😊🙂😌😛😝')
    print('You win ☺️😊🙂😌😛😝')
    print('You win ☺️😊🙂😌😛😝')          #these line line to check who win
    
elif your==1 and computer==0:                
    print('You win ☺️😊🙂😌😛😝')         #these line line to check who win
    print('You win ☺️😊🙂😌😛😝')         
    print('You win ☺️😊🙂😌😛😝')        
    
elif your==2 and computer==1:
    print('You win ☺️😊🙂😌😛😝')
    print('You win ☺️😊🙂😌😛😝')          #these line line to check who win
    print('You win ☺️😊🙂😌😛😝')
    
elif your==computer :
    print('Its an draw 😑🤨')
    print('Its an draw 😑🤨')            #these line line to check when to draw
    print('Its an draw 😑🤨')
    
else:
    print('you lose 😞😔😟😕🙁☹️')    
    print('you lose 😞😔😟😕🙁☹️')    #these line line to check when to loss
    print('you lose 😞😔😟😕🙁☹️')    
    
print(game_image[computer],'is the computer choice')
print(game_image[computer],'is the computer choice')
print(game_image[computer],'is the computer choice')